//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public class CanBaudRate : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CanBaudRate(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CanBaudRate obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CanBaudRate obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CanBaudRate() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NanolibPINVOKE.delete_CanBaudRate(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string BAUD_RATE_1000K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_1000K_get(swigCPtr);
      return ret;
    } 
  }

  public string BAUD_RATE_800K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_800K_get(swigCPtr);
      return ret;
    } 
  }

  public string BAUD_RATE_500K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_500K_get(swigCPtr);
      return ret;
    } 
  }

  public string BAUD_RATE_250K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_250K_get(swigCPtr);
      return ret;
    } 
  }

  public string BAUD_RATE_125K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_125K_get(swigCPtr);
      return ret;
    } 
  }

  public string BAUD_RATE_100K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_100K_get(swigCPtr);
      return ret;
    } 
  }

  public string BAUD_RATE_50K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_50K_get(swigCPtr);
      return ret;
    } 
  }

  public string BAUD_RATE_20K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_20K_get(swigCPtr);
      return ret;
    } 
  }

  public string BAUD_RATE_10K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_10K_get(swigCPtr);
      return ret;
    } 
  }

  public string BAUD_RATE_5K {
    get {
      string ret = NanolibPINVOKE.CanBaudRate_BAUD_RATE_5K_get(swigCPtr);
      return ret;
    } 
  }

  public CanBaudRate() : this(NanolibPINVOKE.new_CanBaudRate(), true) {
  }

}

}
