//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public enum ObjectCode {
  Null = 0x00,
  Deftype = 0x05,
  Defstruct = 0x06,
  Var = 0x07,
  Array = 0x08,
  Record = 0x09
}

}
