//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public enum ObjectEntryDataType {
  Invalid = 0x0000,
  Boolean = 0x0001,
  Integer8 = 0x0002,
  Integer16 = 0x0003,
  Integer32 = 0x0004,
  Unsigned8 = 0x0005,
  Unsigned16 = 0x0006,
  Unsigned32 = 0x0007,
  Real32 = 0x0008,
  VisibleString = 0x0009,
  OctetString = 0x000A,
  UnicodeString = 0x000B,
  TimeOfDay = 0x000C,
  TimeDifference = 0x000D,
  Domain = 0x000F,
  Integer24 = 0x0010,
  Real64 = 0x0011,
  Integer40 = 0x0012,
  Integer48 = 0x0013,
  Integer56 = 0x0014,
  Integer64 = 0x0015,
  Unsigned24 = 0x0016,
  Unsigned40 = 0x0018,
  Unsigned48 = 0x0019,
  Unsigned56 = 0x001A,
  Unsigned64 = 0x001B,
  PdoCommunicationParameter = 0x0020,
  PdoMapping = 0x0021,
  Identity = 0x0023,
  SyncmgrSynchronization = 0x0029,
  UserStorageArea = 0x0040,
  SamplerConfig = 0x0042,
  SamplerTimebase = 0x0043,
  PdiInput = 0x0045,
  PdiOutput = 0x0046,
  ClosedLoopControllerParameter = 0x0047,
  OpenLoopControllerParameter = 0x0048,
  SsiEncoder = 0x0049,
  N2 = 0x0071,
  N4 = 0x0072,
  V2 = 0x0073,
  X2 = 0x007B,
  X4 = 0x007C,
  InterpolationTimePeriod = 0x0080,
  InterpolationDataConfiguration = 0x0081,
  VelocityAccelerationDeceleration = 0x0082,
  Simple = 0x0777,
  Complex = 0x0FFF,
  Unknown = 0xFFFF
}

}
