//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public enum ObjectSaveable {
  APPLICATION,
  COMMUNICATION,
  DRIVE,
  MISC_CONFIG,
  MODBUS_RTU,
  NO,
  TUNING,
  CUSTOMER,
  ETHERNET,
  CANOPEN,
  PROFIBUS,
  VERIFY1020,
  UNKNOWN_SAVEABLE_TYPE
}

}
