// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSGM.Model.DbSoftware;

#nullable disable

namespace PSGM.Model.DbSoftware.Migrations
{
    [DbContext(typeof(DbSoftware_Context))]
    [Migration("20240911152643_InitialeCreate")]
    partial class InitialeCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PSGM.Model.DbSoftware.DbSoftware_Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndOfLife")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndOfLife");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<uint>("ReleaseChannel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReleaseChannel");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReleaseDate");

                    b.Property<uint>("SoftwareType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoftwareType");

                    b.Property<string>("UpdateServer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateServer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("Software");
                });

            modelBuilder.Entity("PSGM.Model.DbSoftware.DbSoftware_Software_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("TEXT")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceId");

                    b.HasKey("Id");

                    b.ToTable("Software_AuditLog");
                });
#pragma warning restore 612, 618
        }
    }
}
