//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public class CanBus : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CanBus(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CanBus obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CanBus() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NanolibPINVOKE.delete_CanBus(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string BAUD_RATE_OPTIONS_NAME {
    get {
      string ret = NanolibPINVOKE.CanBus_BAUD_RATE_OPTIONS_NAME_get(swigCPtr);
      return ret;
    } 
  }

  public CanBaudRate baudRate {
    get {
      global::System.IntPtr cPtr = NanolibPINVOKE.CanBus_baudRate_get(swigCPtr);
      CanBaudRate ret = (cPtr == global::System.IntPtr.Zero) ? null : new CanBaudRate(cPtr, false);
      return ret;
    } 
  }

  public Ixxat ixxat {
    get {
      global::System.IntPtr cPtr = NanolibPINVOKE.CanBus_ixxat_get(swigCPtr);
      Ixxat ret = (cPtr == global::System.IntPtr.Zero) ? null : new Ixxat(cPtr, false);
      return ret;
    } 
  }

  public CanBus() : this(NanolibPINVOKE.new_CanBus(), true) {
  }

}

}
