//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public class DeviceIdVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<DeviceId>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DeviceIdVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DeviceIdVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DeviceIdVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DeviceIdVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NanolibPINVOKE.delete_DeviceIdVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DeviceIdVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (DeviceId element in c) {
      this.Add(element);
    }
  }

  public DeviceIdVector(global::System.Collections.Generic.IEnumerable<DeviceId> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (DeviceId element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public DeviceId this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(DeviceId[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(DeviceId[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, DeviceId[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public DeviceId[] ToArray() {
    DeviceId[] array = new DeviceId[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<DeviceId> global::System.Collections.Generic.IEnumerable<DeviceId>.GetEnumerator() {
    return new DeviceIdVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new DeviceIdVectorEnumerator(this);
  }

  public DeviceIdVectorEnumerator GetEnumerator() {
    return new DeviceIdVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class DeviceIdVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<DeviceId>
  {
    private DeviceIdVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public DeviceIdVectorEnumerator(DeviceIdVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public DeviceId Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (DeviceId)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    NanolibPINVOKE.DeviceIdVector_Clear(swigCPtr);
  }

  public void Add(DeviceId x) {
    NanolibPINVOKE.DeviceIdVector_Add(swigCPtr, DeviceId.getCPtr(x));
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = NanolibPINVOKE.DeviceIdVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = NanolibPINVOKE.DeviceIdVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    NanolibPINVOKE.DeviceIdVector_reserve(swigCPtr, n);
  }

  public DeviceIdVector() : this(NanolibPINVOKE.new_DeviceIdVector__SWIG_0(), true) {
  }

  public DeviceIdVector(DeviceIdVector other) : this(NanolibPINVOKE.new_DeviceIdVector__SWIG_1(DeviceIdVector.getCPtr(other)), true) {
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  public DeviceIdVector(int capacity) : this(NanolibPINVOKE.new_DeviceIdVector__SWIG_2(capacity), true) {
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  private DeviceId getitemcopy(int index) {
    DeviceId ret = new DeviceId(NanolibPINVOKE.DeviceIdVector_getitemcopy(swigCPtr, index), true);
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private DeviceId getitem(int index) {
    DeviceId ret = new DeviceId(NanolibPINVOKE.DeviceIdVector_getitem(swigCPtr, index), false);
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, DeviceId val) {
    NanolibPINVOKE.DeviceIdVector_setitem(swigCPtr, index, DeviceId.getCPtr(val));
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(DeviceIdVector values) {
    NanolibPINVOKE.DeviceIdVector_AddRange(swigCPtr, DeviceIdVector.getCPtr(values));
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  public DeviceIdVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = NanolibPINVOKE.DeviceIdVector_GetRange(swigCPtr, index, count);
    DeviceIdVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeviceIdVector(cPtr, true);
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, DeviceId x) {
    NanolibPINVOKE.DeviceIdVector_Insert(swigCPtr, index, DeviceId.getCPtr(x));
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, DeviceIdVector values) {
    NanolibPINVOKE.DeviceIdVector_InsertRange(swigCPtr, index, DeviceIdVector.getCPtr(values));
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    NanolibPINVOKE.DeviceIdVector_RemoveAt(swigCPtr, index);
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    NanolibPINVOKE.DeviceIdVector_RemoveRange(swigCPtr, index, count);
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  public static DeviceIdVector Repeat(DeviceId value, int count) {
    global::System.IntPtr cPtr = NanolibPINVOKE.DeviceIdVector_Repeat(DeviceId.getCPtr(value), count);
    DeviceIdVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeviceIdVector(cPtr, true);
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    NanolibPINVOKE.DeviceIdVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    NanolibPINVOKE.DeviceIdVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, DeviceIdVector values) {
    NanolibPINVOKE.DeviceIdVector_SetRange(swigCPtr, index, DeviceIdVector.getCPtr(values));
    if (NanolibPINVOKE.SWIGPendingException.Pending) throw NanolibPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
