//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public class Ixxat : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Ixxat(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Ixxat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Ixxat() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NanolibPINVOKE.delete_Ixxat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string ADAPTER_BUS_NUMBER_OPTIONS_NAME {
    get {
      string ret = NanolibPINVOKE.Ixxat_ADAPTER_BUS_NUMBER_OPTIONS_NAME_get(swigCPtr);
      return ret;
    } 
  }

  public IxxatAdapterBusNumber adapterBusNumber {
    get {
      global::System.IntPtr cPtr = NanolibPINVOKE.Ixxat_adapterBusNumber_get(swigCPtr);
      IxxatAdapterBusNumber ret = (cPtr == global::System.IntPtr.Zero) ? null : new IxxatAdapterBusNumber(cPtr, false);
      return ret;
    } 
  }

  public Ixxat() : this(NanolibPINVOKE.new_Ixxat(), true) {
  }

}

}
