//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public enum ObjectPdoAccessAttribute {
  Tx = 1,
  Rx = 2,
  TxRx = 3,
  No = 0
}

}
