//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public enum ObjectSdoAccessAttribute {
  ReadOnly = 1,
  WriteOnly = 2,
  ReadWrite = 3,
  NoAccess = 0
}

}
