// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSGM.Model.DbMain;

#nullable disable

namespace PSGM.Model.DbMain.Migrations
{
    [DbContext(typeof(DbMain_Context))]
    partial class DbMain_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("psgm")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AddressLinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("City");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CountryName");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<int>("GpsAltitude")
                        .HasColumnType("integer")
                        .HasColumnName("GpsAltitude");

                    b.Property<char>("GpsLatitudeCardinalPoint")
                        .HasColumnType("character(1)")
                        .HasColumnName("GpsLatitudeCardinalPoint");

                    b.Property<decimal>("GpsLatitudeDegree")
                        .HasColumnType("numeric")
                        .HasColumnName("GpsLatitudeDegree");

                    b.Property<decimal>("GpsLatitudeMinute")
                        .HasColumnType("numeric")
                        .HasColumnName("GpsLatitudeMinute");

                    b.Property<decimal>("GpsLatitudeSecond")
                        .HasColumnType("numeric")
                        .HasColumnName("GpsLatitudeSecond");

                    b.Property<char>("GpsLongitudeCardinalPoint")
                        .HasColumnType("character(1)")
                        .HasColumnName("GpsLongitudeCardinalPoint");

                    b.Property<decimal>("GpsLongitudeDegree")
                        .HasColumnType("numeric")
                        .HasColumnName("GpsLongitudeDegree");

                    b.Property<decimal>("GpsLongitudeMinute")
                        .HasColumnType("numeric")
                        .HasColumnName("GpsLongitudeMinute");

                    b.Property<decimal>("GpsLongitudeSecond")
                        .HasColumnType("numeric")
                        .HasColumnName("GpsLongitudeSecond");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Line1");

                    b.Property<string>("Line2")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Line2");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("RegionCode");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("RegionName");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.ToTable("Address", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Address_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Address_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Contributors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("ContributorType")
                        .HasColumnType("integer")
                        .HasColumnName("ContributorType");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)")
                        .HasColumnName("Description");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Contributors", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Contributors_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Contributors_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DeliverySlip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<bool>("DeliverySlipIsDirectory")
                        .HasColumnType("boolean")
                        .HasColumnName("DeliverySlipIsDirectory");

                    b.Property<long>("DeliverySlipState")
                        .HasMaxLength(1023)
                        .HasColumnType("bigint")
                        .HasColumnName("DeliverySliplState");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)")
                        .HasColumnName("Description");

                    b.Property<string>("DocumentObjectName")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)")
                        .HasColumnName("DocumentObjectName");

                    b.Property<Guid>("ExternalContactUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("ExternalContactUserIdExt");

                    b.Property<Guid>("ExternalContributorsUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("ExternalContributorsUserIdExt");

                    b.Property<Guid>("InternalContactUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("InternalContactUserIdExt");

                    b.Property<Guid>("InternalContributorsUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("InternalContributorsUserIdExt");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("ProcessingFinishedDateTime")
                        .HasMaxLength(1023)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessingFinishedDateTime");

                    b.Property<Guid>("ProcessingFinishedUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("ProcessingFinishedUserIdExt");

                    b.Property<DateTime>("ProcessingStartedDateTime")
                        .HasMaxLength(1023)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessingStartedDateTime");

                    b.Property<Guid>("ProcessingStartedUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("ProcessingStartedUserIdExt");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("DeliverySlip", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DeliverySlip_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("DeliverySlip_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DeliverySlip_Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("DeliverySlipDocumentObjectName")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)")
                        .HasColumnName("DeliverySlipDocumentObjectName");

                    b.Property<Guid?>("DeliverySlipId")
                        .HasColumnType("uuid");

                    b.Property<long>("DeliverySlipState")
                        .HasMaxLength(1023)
                        .HasColumnType("bigint")
                        .HasColumnName("DeliverySlipState");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)")
                        .HasColumnName("Description");

                    b.Property<Guid>("ExternalContactUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("ExternalContactUserIdExt");

                    b.Property<Guid>("ExternalContributorsUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("ExternalContributorsUserIdExt");

                    b.Property<Guid>("InternalContactUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("InternalContactUserIdExt");

                    b.Property<Guid>("InternalContributorsUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("InternalContributorsUserIdExt");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("OderProcessingFinishedDateTime")
                        .HasMaxLength(1023)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OderProcessingFinishedDateTime");

                    b.Property<Guid>("OderProcessingFinishedUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("OderProcessingFinishedUserIdExt");

                    b.Property<DateTime>("OderProcessingStartedDateTime")
                        .HasMaxLength(1023)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OderProcessingStartedDateTime");

                    b.Property<Guid>("OderProcessingStartedUserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("OderProcessingStartedUserIdExt");

                    b.HasKey("Id");

                    b.HasIndex("DeliverySlipId")
                        .IsUnique();

                    b.ToTable("DeliverySlip_Template", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DeliverySlip_Template_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("DeliverySlip_Template_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<Guid?>("DeliverySlipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("Finished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Finished");

                    b.Property<string>("MachinesExtString")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("MachinesExtString");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Started");

                    b.Property<long>("Status")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<long>("WorkflowApplyLevel")
                        .HasColumnType("bigint")
                        .HasColumnName("WorkflowApplyLevel");

                    b.Property<Guid>("WorkflowIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowIdExt");

                    b.HasKey("Id");

                    b.HasIndex("DeliverySlipId");

                    b.ToTable("DocumentType", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DocumentType_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("DocumentType_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Location", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Location_Address_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("Location_Address_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Location_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Location_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Acronym");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("DaytimePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("DaytimePhoneNumber");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)")
                        .HasColumnName("EMail");

                    b.Property<string>("EveningPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("EveningPhoneNumber");

                    b.Property<string>("Homepage")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)")
                        .HasColumnName("Homepage");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Organization", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Organization_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("Permissions");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Organization_Authorization_User", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("Permissions");

                    b.Property<Guid>("UserGroupIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserGroupIdExt");

                    b.HasKey("Id");

                    b.ToTable("Organization_Authorization_UserGroup", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_UserGroup_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Organization_Authorization_UserGroup_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_UserGroup_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AuthorizationUserGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationUserGroupId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Organization_Authorization_UserGroup_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_User_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Organization_Authorization_User_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_User_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AuthorizationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Organization_Authorization_User_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Location_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Organization_Location_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<bool>("EMail")
                        .HasColumnType("boolean")
                        .HasColumnName("EMail");

                    b.Property<bool>("Gotify")
                        .HasColumnType("boolean")
                        .HasColumnName("Gotify");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("NotificationType");

                    b.Property<bool>("SMS")
                        .HasColumnType("boolean")
                        .HasColumnName("SMS");

                    b.Property<bool>("Slack")
                        .HasColumnType("boolean")
                        .HasColumnName("Slack");

                    b.Property<bool>("Teams")
                        .HasColumnType("boolean")
                        .HasColumnName("Teams");

                    b.Property<bool>("Telegram")
                        .HasColumnType("boolean")
                        .HasColumnName("Telegram");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.Property<bool>("WhatsApp")
                        .HasColumnType("boolean")
                        .HasColumnName("WhatsApp");

                    b.HasKey("Id");

                    b.ToTable("Organization_Notification_User", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<bool>("EMail")
                        .HasColumnType("boolean")
                        .HasColumnName("EMail");

                    b.Property<bool>("Gotify")
                        .HasColumnType("boolean")
                        .HasColumnName("Gotify");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("NotificationType");

                    b.Property<bool>("SMS")
                        .HasColumnType("boolean")
                        .HasColumnName("SMS");

                    b.Property<bool>("Slack")
                        .HasColumnType("boolean")
                        .HasColumnName("Slack");

                    b.Property<bool>("Teams")
                        .HasColumnType("boolean")
                        .HasColumnName("Teams");

                    b.Property<bool>("Telegram")
                        .HasColumnType("boolean")
                        .HasColumnName("Telegram");

                    b.Property<Guid>("UserGroupIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserGroupIdExt");

                    b.Property<bool>("WhatsApp")
                        .HasColumnType("boolean")
                        .HasColumnName("WhatsApp");

                    b.HasKey("Id");

                    b.ToTable("Organization_Notification_UserGroup", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_UserGroup_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Organization_Notification_UserGroup_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_UserGroup_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("NotificationUserGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationUserGroupId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Organization_Notification_UserGroup_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_User_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Organization_Notification_User_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_User_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("NotificationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Organization_Notification_User_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("AqlAcceptableQualityLevelImage")
                        .HasColumnType("integer")
                        .HasColumnName("AqlAcceptableQualityLevelImage");

                    b.Property<int>("AqlAcceptableQualityLevelTranscription")
                        .HasColumnType("integer")
                        .HasColumnName("AqlAcceptableQualityLevelTranscription");

                    b.Property<int>("AqlInspectionLevelImage")
                        .HasColumnType("integer")
                        .HasColumnName("AqlInspectionLevelImage");

                    b.Property<int>("AqlInspectionLevelTranscription")
                        .HasColumnType("integer")
                        .HasColumnName("AqlInspectionLevelTranscription");

                    b.Property<int>("AqlQuantityImage")
                        .HasColumnType("integer")
                        .HasColumnName("AqlQuantityImage");

                    b.Property<int>("AqlQuantityTranscription")
                        .HasColumnType("integer")
                        .HasColumnName("AqlQuantityTranscription");

                    b.Property<int>("AqlStateImage")
                        .HasColumnType("integer")
                        .HasColumnName("AqlStateImage");

                    b.Property<DateTime>("AqlStateLastChangeImage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AqlStateLastChangeImage");

                    b.Property<DateTime>("AqlStateLastChangeTranscription")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AqlStateLastChangeTranscription");

                    b.Property<int>("AqlStateTranscription")
                        .HasColumnType("integer")
                        .HasColumnName("AqlStateTranscription");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("Finished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Finished");

                    b.Property<string>("MachinesExtString")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("MachinesExtString");

                    b.Property<long>("MaxDirectorySize")
                        .HasColumnType("bigint")
                        .HasColumnName("MaxDirectorySize");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Started");

                    b.Property<long>("Status")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<long>("WorkflowApplyLevel")
                        .HasColumnType("bigint")
                        .HasColumnName("WorkflowApplyLevel");

                    b.Property<Guid>("WorkflowIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowIdExt");

                    b.HasKey("Id");

                    b.ToTable("Project", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Project_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("Permissions");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Project_Authorization_User", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("Permissions");

                    b.Property<Guid>("UserGroupIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserGroupIdExt");

                    b.HasKey("Id");

                    b.ToTable("Project_Authorization_UserGroup", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_UserGroup_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Project_Authorization_UserGroup_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_UserGroup_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AuthorizationUserGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationUserGroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Project_Authorization_UserGroup_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_User_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Project_Authorization_User_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_User_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AuthorizationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Project_Authorization_User_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Location_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Project_Location_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<bool>("EMail")
                        .HasColumnType("boolean")
                        .HasColumnName("EMail");

                    b.Property<bool>("Gotify")
                        .HasColumnType("boolean")
                        .HasColumnName("Gotify");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("NotificationType");

                    b.Property<bool>("SMS")
                        .HasColumnType("boolean")
                        .HasColumnName("SMS");

                    b.Property<bool>("Slack")
                        .HasColumnType("boolean")
                        .HasColumnName("Slack");

                    b.Property<bool>("Teams")
                        .HasColumnType("boolean")
                        .HasColumnName("Teams");

                    b.Property<bool>("Telegram")
                        .HasColumnType("boolean")
                        .HasColumnName("Telegram");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.Property<bool>("WhatsApp")
                        .HasColumnType("boolean")
                        .HasColumnName("WhatsApp");

                    b.HasKey("Id");

                    b.ToTable("Project_Notification_User", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("Description");

                    b.Property<bool>("EMail")
                        .HasColumnType("boolean")
                        .HasColumnName("EMail");

                    b.Property<bool>("Gotify")
                        .HasColumnType("boolean")
                        .HasColumnName("Gotify");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("NotificationType");

                    b.Property<bool>("SMS")
                        .HasColumnType("boolean")
                        .HasColumnName("SMS");

                    b.Property<bool>("Slack")
                        .HasColumnType("boolean")
                        .HasColumnName("Slack");

                    b.Property<bool>("Teams")
                        .HasColumnType("boolean")
                        .HasColumnName("Teams");

                    b.Property<bool>("Telegram")
                        .HasColumnType("boolean")
                        .HasColumnName("Telegram");

                    b.Property<Guid>("UserGroupIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserGroupIdExt");

                    b.Property<bool>("WhatsApp")
                        .HasColumnType("boolean")
                        .HasColumnName("WhatsApp");

                    b.HasKey("Id");

                    b.ToTable("Project_Notification_UserGroup", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_UserGroup_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Project_Notification_UserGroup_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_UserGroup_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("NotificationUserGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationUserGroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Project_Notification_UserGroup_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_User_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Project_Notification_User_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_User_Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("NotificationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Project_Notification_User_Link", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("BackupsExtString")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("BackupsExtString");

                    b.Property<Guid>("CreatedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserIdExtAutoFill");

                    b.Property<DateTime>("CreatedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTimeAutoFill");

                    b.Property<Guid?>("DeliverySlipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)")
                        .HasColumnName("Description");

                    b.Property<long>("DirectorySize")
                        .HasColumnType("bigint")
                        .HasColumnName("DirectorySize");

                    b.Property<bool>("DocumentType")
                        .HasColumnType("boolean")
                        .HasColumnName("DocumentType");

                    b.Property<string>("JobsIdExtString")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("JobsIdExtString");

                    b.Property<string>("LastModificationChanges")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)")
                        .HasColumnName("LastModificationChanges");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean")
                        .HasColumnName("Locked");

                    b.Property<Guid>("ModifiedByUserIdExtAutoFill")
                        .HasColumnType("uuid")
                        .HasColumnName("ModifiedByUserIdExtAutoFill");

                    b.Property<DateTime>("ModifiedDateTimeAutoFill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDateTimeAutoFill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Name");

                    b.Property<long>("Objects")
                        .HasColumnType("bigint")
                        .HasColumnName("Objects");

                    b.Property<Guid?>("ParentUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("Suffix");

                    b.Property<string>("WorkflowItemsExtString")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("WorkflowItemExtString");

                    b.HasKey("Id");

                    b.HasIndex("DeliverySlipId");

                    b.HasIndex("ParentUnitId");

                    b.ToTable("Unit", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Unit_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("character varying(16383)")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SoftwareIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("SoftwareIdExt");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<Guid>("UserIdExt")
                        .HasColumnType("uuid")
                        .HasColumnName("UserIdExt");

                    b.HasKey("Id");

                    b.ToTable("Unit_AuditLog", "psgm");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Contributors", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization", "Organization")
                        .WithMany("Contributors")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Project", "Project")
                        .WithMany("Contributors")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Organization");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DeliverySlip", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Project", "Project")
                        .WithOne("DeliverySlip")
                        .HasForeignKey("PSGM.Model.DbMain.DbMain_DeliverySlip", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DeliverySlip_Template", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_DeliverySlip", "DeliverySlip")
                        .WithOne("CreatedWithDeliverySlipTemplate")
                        .HasForeignKey("PSGM.Model.DbMain.DbMain_DeliverySlip_Template", "DeliverySlipId");

                    b.Navigation("DeliverySlip");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DocumentType", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_DeliverySlip", "DeliverySlip")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("DeliverySlipId");

                    b.Navigation("DeliverySlip");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Location_Address_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Address", "Address")
                        .WithOne("AddressLink")
                        .HasForeignKey("PSGM.Model.DbMain.DbMain_Location_Address_Link", "AddressId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Location", "Location")
                        .WithOne("AddressLink")
                        .HasForeignKey("PSGM.Model.DbMain.DbMain_Location_Address_Link", "LocationId");

                    b.Navigation("Address");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Project", "Project")
                        .WithOne("Organization")
                        .HasForeignKey("PSGM.Model.DbMain.DbMain_Organization", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_UserGroup_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization_Authorization_UserGroup", "AuthorizationUserGroup")
                        .WithMany("AuthorizationUserGroupLinks")
                        .HasForeignKey("AuthorizationUserGroupId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization", "Organization")
                        .WithMany("AuthorizationUserGroupLinks")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("AuthorizationUserGroup");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_User_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization_Authorization_User", "AuthorizationUser")
                        .WithMany("AuthorizationUserLinks")
                        .HasForeignKey("AuthorizationUserId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization", "Organization")
                        .WithMany("AuthorizationUserLinks")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("AuthorizationUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Location_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Location", "Location")
                        .WithMany("OrganizationLocationLink")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization", "Organization")
                        .WithMany("LocationLinks")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Location");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_UserGroup_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization_Notification_UserGroup", "NotificationUserGroup")
                        .WithMany("NotificationUserGroupLinks")
                        .HasForeignKey("NotificationUserGroupId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization", "Organization")
                        .WithMany("NotificationUserGroupLinks")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("NotificationUserGroup");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_User_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization_Notification_User", "NotificationUser")
                        .WithMany("NotificationUserLinks")
                        .HasForeignKey("NotificationUserId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Organization", "Organization")
                        .WithMany("NotificationUserLinks")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("NotificationUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_UserGroup_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Project_Authorization_UserGroup", "AuthorizationUserGroup")
                        .WithMany("AuthorizationUserGroupLinks")
                        .HasForeignKey("AuthorizationUserGroupId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Project", "Project")
                        .WithMany("AuthorizationUserGroupLinks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("AuthorizationUserGroup");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_User_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Project_Authorization_User", "AuthorizationUser")
                        .WithMany("AuthorizationUserLinks")
                        .HasForeignKey("AuthorizationUserId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Project", "Project")
                        .WithMany("AuthorizationUserLinks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("AuthorizationUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Location_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Location", "Location")
                        .WithMany("ProjectLocationLink")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSGM.Model.DbMain.DbMain_Project", "Project")
                        .WithMany("LocationLinks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Location");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_UserGroup_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Project_Notification_UserGroup", "NotificationUserGroup")
                        .WithMany("NotificationUserGroupLinks")
                        .HasForeignKey("NotificationUserGroupId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Project", "Project")
                        .WithMany("NotificationUserGroupLinks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("NotificationUserGroup");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_User_Link", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_Project_Notification_User", "NotificationUser")
                        .WithMany("NotificationUserLinks")
                        .HasForeignKey("NotificationUserId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Project", "Project")
                        .WithMany("NotificationUserLinks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("NotificationUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Unit", b =>
                {
                    b.HasOne("PSGM.Model.DbMain.DbMain_DeliverySlip", "DeliverySlip")
                        .WithMany("Units")
                        .HasForeignKey("DeliverySlipId");

                    b.HasOne("PSGM.Model.DbMain.DbMain_Unit", "ParentUnit")
                        .WithMany("Unit")
                        .HasForeignKey("ParentUnitId");

                    b.Navigation("DeliverySlip");

                    b.Navigation("ParentUnit");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Address", b =>
                {
                    b.Navigation("AddressLink");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_DeliverySlip", b =>
                {
                    b.Navigation("CreatedWithDeliverySlipTemplate");

                    b.Navigation("DocumentTypes");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Location", b =>
                {
                    b.Navigation("AddressLink");

                    b.Navigation("OrganizationLocationLink");

                    b.Navigation("ProjectLocationLink");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization", b =>
                {
                    b.Navigation("AuthorizationUserGroupLinks");

                    b.Navigation("AuthorizationUserLinks");

                    b.Navigation("Contributors");

                    b.Navigation("LocationLinks");

                    b.Navigation("NotificationUserGroupLinks");

                    b.Navigation("NotificationUserLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_User", b =>
                {
                    b.Navigation("AuthorizationUserLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Authorization_UserGroup", b =>
                {
                    b.Navigation("AuthorizationUserGroupLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_User", b =>
                {
                    b.Navigation("NotificationUserLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Organization_Notification_UserGroup", b =>
                {
                    b.Navigation("NotificationUserGroupLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project", b =>
                {
                    b.Navigation("AuthorizationUserGroupLinks");

                    b.Navigation("AuthorizationUserLinks");

                    b.Navigation("Contributors");

                    b.Navigation("DeliverySlip");

                    b.Navigation("LocationLinks");

                    b.Navigation("NotificationUserGroupLinks");

                    b.Navigation("NotificationUserLinks");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_User", b =>
                {
                    b.Navigation("AuthorizationUserLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Authorization_UserGroup", b =>
                {
                    b.Navigation("AuthorizationUserGroupLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_User", b =>
                {
                    b.Navigation("NotificationUserLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Project_Notification_UserGroup", b =>
                {
                    b.Navigation("NotificationUserGroupLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbMain.DbMain_Unit", b =>
                {
                    b.Navigation("Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
