// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSGM.Model.DbWorkflow;

#nullable disable

namespace PSGM.Model.DbWorkflow.Migrations
{
    [DbContext(typeof(DbWorkflow_Context))]
    partial class DbWorkflow_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PSGM.Model.DbWorkflow.DbWorkflow_Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Workflow");
                });

            modelBuilder.Entity("PSGM.Model.DbWorkflow.DbWorkflow_WorkflowItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<uint>("ApplyLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApplyLevel");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT")
                        .HasColumnName("Configuration");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<uint>("WorkflowExecutionLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("WorkflowExecutionLevel");

                    b.HasKey("Id");

                    b.ToTable("WorkflowItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef601faa-1bb5-4171-b907-60a2f1935eee"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Save object (depending on storage configuration in project parameters) to specified S3 storage or filesystem and add the file entity to the database...",
                            Name = "Save object to S3 storage or filesystem and add entity to database - V1.0.0",
                            WorkflowExecutionLevel = 0u
                        },
                        new
                        {
                            Id = new Guid("f03093f8-6ea8-4bee-9875-30d1fc7975f3"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Grab image with specified camera ...",
                            Name = "Grab image - V1.0.0",
                            WorkflowExecutionLevel = 0u
                        },
                        new
                        {
                            Id = new Guid("4d7723ce-5bcd-4f82-a921-f9621fa5c383"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Calculate HDR image with OpenCV (mergeMertens) ...",
                            Name = "Calculate HDR image - V1.0.0",
                            WorkflowExecutionLevel = 0u
                        },
                        new
                        {
                            Id = new Guid("68299067-b79b-4120-98df-13a3e2232c88"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Calculate darktable image according to the sidecar file ...",
                            Name = "Calculate darktable image - V1.0.0",
                            WorkflowExecutionLevel = 0u
                        },
                        new
                        {
                            Id = new Guid("c33c011d-229a-4c3d-af44-05db3a4c7af4"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Resize image to specified size...",
                            Name = "Resize image - V1.0.0",
                            WorkflowExecutionLevel = 0u
                        },
                        new
                        {
                            Id = new Guid("c2dc5eed-f926-4615-882f-c8184c981d93"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Crop image to specified size...",
                            Name = "Crop image - V1.0.0",
                            WorkflowExecutionLevel = 0u
                        },
                        new
                        {
                            Id = new Guid("0f10bb0b-f782-4e5b-a53b-c75f7c0403fb"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Rotate image ...",
                            Name = "Rotate image - V1.0.0",
                            WorkflowExecutionLevel = 0u
                        },
                        new
                        {
                            Id = new Guid("fd184c53-2e4a-4384-8894-3639eef8ea66"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Rotate image ...",
                            Name = "Rotate image - V2.0.0",
                            WorkflowExecutionLevel = 0u
                        },
                        new
                        {
                            Id = new Guid("38905667-b47b-4d23-b149-c500372f0eff"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Sharpen image ...",
                            Name = "Sharpen image - V1.0.0",
                            WorkflowExecutionLevel = 0u
                        },
                        new
                        {
                            Id = new Guid("083c3d9a-0915-4506-bf60-b164d19071df"),
                            ApplyLevel = 10000u,
                            Configuration = "",
                            Description = "Sharpen image ...",
                            Name = "Sharpen image - V2.0.0",
                            WorkflowExecutionLevel = 0u
                        });
                });

            modelBuilder.Entity("PSGM.Model.DbWorkflow.DbWorkflow_WorkflowItemLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<uint>("ApplyLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApplyLevel");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT")
                        .HasColumnName("Configuration");

                    b.Property<int>("ExecutionPermissions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExecutionPermissions");

                    b.Property<uint>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Order");

                    b.Property<uint>("StorageClass")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StorageClass");

                    b.Property<uint>("StorageType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StorageType");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("WorkflowItemId");

                    b.ToTable("WorkflowItemLink");
                });

            modelBuilder.Entity("PSGM.Model.DbWorkflow.DbWorkflow_WorkflowItemLink_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("TEXT")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceId");

                    b.HasKey("Id");

                    b.ToTable("WorkflowItemLink_AuditLog");
                });

            modelBuilder.Entity("PSGM.Model.DbWorkflow.DbWorkflow_WorkflowItem_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("TEXT")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceId");

                    b.HasKey("Id");

                    b.ToTable("WorkflowItem_AuditLog");
                });

            modelBuilder.Entity("PSGM.Model.DbWorkflow.DbWorkflow_Workflow_AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(16383)
                        .HasColumnType("TEXT")
                        .HasColumnName("Changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateTime");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceId");

                    b.HasKey("Id");

                    b.ToTable("Workflow_AuditLog");
                });

            modelBuilder.Entity("PSGM.Model.DbWorkflow.DbWorkflow_WorkflowItemLink", b =>
                {
                    b.HasOne("PSGM.Model.DbWorkflow.DbWorkflow_Workflow", "Workflow")
                        .WithMany("WorkflowItemLinks")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSGM.Model.DbWorkflow.DbWorkflow_WorkflowItem", "WorkflowItem")
                        .WithMany("WorkflowItemLinks")
                        .HasForeignKey("WorkflowItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");

                    b.Navigation("WorkflowItem");
                });

            modelBuilder.Entity("PSGM.Model.DbWorkflow.DbWorkflow_Workflow", b =>
                {
                    b.Navigation("WorkflowItemLinks");
                });

            modelBuilder.Entity("PSGM.Model.DbWorkflow.DbWorkflow_WorkflowItem", b =>
                {
                    b.Navigation("WorkflowItemLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
