//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public enum SamplerTriggerCondition {
  TC_FALSE = 0x00,
  TC_TRUE = 0x01,
  TC_SET = 0x10,
  TC_CLEAR = 0x11,
  TC_RISING_EDGE = 0x12,
  TC_FALLING_EDGE = 0x13,
  TC_BIT_TOGGLE = 0x14,
  TC_GREATER = 0x15,
  TC_GREATER_OR_EQUAL = 0x16,
  TC_LESS = 0x17,
  TC_LESS_OR_EQUAL = 0x18,
  TC_EQUAL = 0x19,
  TC_NOT_EQUAL = 0x1A,
  TC_ONE_EDGE = 0x1B,
  TC_MULTI_EDGE = 0x1C
}

}
