//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace  Nlc {

public class Serial : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Serial(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Serial obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Serial() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NanolibPINVOKE.delete_Serial(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string BAUD_RATE_OPTIONS_NAME {
    get {
      string ret = NanolibPINVOKE.Serial_BAUD_RATE_OPTIONS_NAME_get(swigCPtr);
      return ret;
    } 
  }

  public SerialBaudRate baudRate {
    get {
      global::System.IntPtr cPtr = NanolibPINVOKE.Serial_baudRate_get(swigCPtr);
      SerialBaudRate ret = (cPtr == global::System.IntPtr.Zero) ? null : new SerialBaudRate(cPtr, false);
      return ret;
    } 
  }

  public string PARITY_OPTIONS_NAME {
    get {
      string ret = NanolibPINVOKE.Serial_PARITY_OPTIONS_NAME_get(swigCPtr);
      return ret;
    } 
  }

  public SerialParity parity {
    get {
      global::System.IntPtr cPtr = NanolibPINVOKE.Serial_parity_get(swigCPtr);
      SerialParity ret = (cPtr == global::System.IntPtr.Zero) ? null : new SerialParity(cPtr, false);
      return ret;
    } 
  }

  public Serial() : this(NanolibPINVOKE.new_Serial(), true) {
  }

}

}
